name: skma_smartapp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  dio: ^5.9.0
  hooks_riverpod: ^3.0.3
  go_router: ^16.2.5
  json_annotation: 4.8.1
  video_player: ^2.10.0
  hive: ^2.2.3
  freezed_annotation: 2.4.1
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  json_serializable: 6.7.1
  freezed: 2.5.2
  build_runner: 2.4.11

flutter:
  uses-material-design: true
  generate: true
flutter_intl:
  enabled: true
